# travis-ci.org 即将关闭开始收费了，暂时不用了

language: node_js

node_js:
  - "12"

env:
  global:
    - CI: false

before_install:

install:
  - npm install

before_script:

script:
  - npm run build:docs

# 分支白名单
branches:
  only:
    - feature

# GitHub Pages 部署
before_deploy:

deploy:
  provider: pages
  skip_cleanup: true
  # 令牌秘钥，在主页面用户的 Setting 中创建
  github_token: $GITHUB_TOKEN
  # 将 dist 目录下的内容推送到默认的 gh-pages 分支上
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: feature
